services:
  rsts:
    image: ghcr.io/ccev/rsts:latest
    ports:
      - "3001:3001"
    volumes:
      - ./rsts.toml:/app/rsts.toml
      - ./data:/app/data
    depends_on:
      - martin
    restart: unless-stopped

  martin:
    image: ghcr.io/maplibre/martin:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db/db
    volumes:
      - ./data:/data
      - ./martin.yml:/config.yml
    command: --config /config.yml
    depends_on:
      - db

  db:
    image: docker.io/postgis/postgis:17-3.5-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pg_data:/var/lib/postgresql/data